### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by symphonyalpha** [jaypyles/obsidian-to-bookstack#1]
Hi. 

I attempted to run `pip3 install .` after cloning the repo, but this was the output that I received. 

```bash
Processing /home/[user]/obsidian-to-bookstack
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1791 sha256=f67ed898358c271c49644b364075f741bba7813a9fec14e6773353e2b8fb43b8
  Stored in directory: /root/.cache/pip/wheels/33/14/94/5d56d8845a81dd20d28226f5d4c214057f9eb5cf5277783f8d
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
```

Is this expected output? After which I tried to run any of the commands (`sync`, `update` etc. ) but none of them worked. 

I'm trying out this program alongside Bookstack for the first time so I'm unsure if I'm just running the commands wrongly. 

Thanks in advance.

**Comment by jaypyles** [comment]
Try installing using pipx and running `pipx install .` in the repo 
https://github.com/pypa/pipx

**Comment by symphonyalpha** [comment]
Thanks for the clarification. I thought the `x` in `pipx` referred to a specific version.
